/**
 * Flag artwork for an ISO-3166-1 alpha-2 code.
 *
 * The files under assets/flags are generated by scripts/make-flags.mjs from
 * Flag Icons (MIT) and committed, so nothing here reaches for a CDN — a Komari
 * install is frequently on a LAN or an air-gapped box.
 *
 * Shipped as separate files rather than inlined into the bundle. There are 250
 * of them and about 1.5 MB in total, of which a given fleet shows a handful:
 * as URLs the browser fetches only the countries actually on screen and caches
 * them, while inlining would put every flag on the critical path of the first
 * paint. `no-inline` is what holds that — Vite inlines assets under 4 KB by
 * default, and most flags are well under it.
 *
 * The glob is eager on purpose. It resolves to 250 URL strings, not to 250
 * chunks: a lazy glob would compile to dynamic imports, and Komari's SPA
 * fallback answers a missing chunk with index.html as text/html rather than a
 * 404, so a stale one fails the render outright. A missing image only loses the
 * picture — see RegionTag, which drops it and keeps the code.
 */

const FILES = import.meta.glob("../assets/flags/*.svg", {
  query: "?url&no-inline",
  import: "default",
  eager: true,
}) as Record<string, string>;

const BY_CODE = new Map(
  Object.entries(FILES).map(([path, url]) => [
    path.slice(path.lastIndexOf("/") + 1, -".svg".length).toUpperCase(),
    url,
  ]),
);

/** The flag for an alpha-2 code, or undefined if this build ships none. */
export function flagUrl(code: string): string | undefined {
  return BY_CODE.get(code);
}
