#!/usr/bin/env node
/**
 * Generates preview.png — the image the Komari admin panel and the theme market
 * show for this theme.
 *
 * Drawn procedurally rather than checked in as a binary so it stays in sync
 * with the palette in src/styles/theme.css and can be regenerated by anyone.
 * Replace it with a real screenshot once you have the theme running against
 * your own fleet; this exists so the package is valid from the first commit.
 *
 * Zero dependencies: a minimal RGBA -> PNG encoder using node:zlib.
 */

import { deflateSync } from "node:zlib";
import { writeFileSync } from "node:fs";

const W = 1200;
const H = 630;

/* ================================================================== *
 * Palette — mirrors the dark token set in src/styles/theme.css
 * ================================================================== */

const BG = [13, 17, 23];
const TEXT = [242, 245, 247];
const MUTED = [169, 180, 190];
const FAINT = [118, 130, 142];
const LINE = [160, 180, 200];
const ACCENT = [70, 214, 232];
const OK = [95, 224, 176];
const WARN = [240, 198, 116];
const BAD = [242, 109, 109];

/* ================================================================== *
 * Canvas
 * ================================================================== */

const buf = new Uint8Array(W * H * 4);

function clear([r, g, b]) {
  for (let i = 0; i < W * H; i++) {
    buf[i * 4] = r;
    buf[i * 4 + 1] = g;
    buf[i * 4 + 2] = b;
    buf[i * 4 + 3] = 255;
  }
}

/** Source-over blend of one pixel. */
function px(x, y, [r, g, b], a = 1) {
  if (a <= 0) return;
  const xi = Math.round(x);
  const yi = Math.round(y);
  if (xi < 0 || yi < 0 || xi >= W || yi >= H) return;
  const i = (yi * W + xi) * 4;
  const alpha = Math.min(1, a);
  buf[i] = buf[i] * (1 - alpha) + r * alpha;
  buf[i + 1] = buf[i + 1] * (1 - alpha) + g * alpha;
  buf[i + 2] = buf[i + 2] * (1 - alpha) + b * alpha;
}

function rect(x, y, w, h, color, a = 1) {
  for (let yy = y; yy < y + h; yy++) {
    for (let xx = x; xx < x + w; xx++) px(xx, yy, color, a);
  }
}

function frame(x, y, w, h, color, a = 1) {
  rect(x, y, w, 1, color, a);
  rect(x, y + h - 1, w, 1, color, a);
  rect(x, y, 1, h, color, a);
  rect(x + w - 1, y, 1, h, color, a);
}

function line(x0, y0, x1, y1, color, a = 1) {
  const dx = Math.abs(x1 - x0);
  const dy = Math.abs(y1 - y0);
  const steps = Math.max(dx, dy, 1);
  for (let i = 0; i <= steps; i++) {
    px(x0 + ((x1 - x0) * i) / steps, y0 + ((y1 - y0) * i) / steps, color, a);
  }
}

/** Arc from `from` degrees sweeping `sweep` degrees, clockwise, 0 deg = east. */
function arc(cx, cy, radius, from, sweep, thickness, color, a = 1) {
  const steps = Math.max(24, Math.abs(sweep) * 2.2);
  for (let i = 0; i <= steps; i++) {
    const deg = from + (sweep * i) / steps;
    const rad = (deg * Math.PI) / 180;
    for (let t = -thickness / 2; t <= thickness / 2; t += 0.4) {
      px(cx + Math.cos(rad) * (radius + t), cy + Math.sin(rad) * (radius + t), color, a);
    }
  }
}

function diamond(cx, cy, r, color, a = 1) {
  for (let dy = -r; dy <= r; dy++) {
    const span = r - Math.abs(dy);
    for (let dx = -span; dx <= span; dx++) px(cx + dx, cy + dy, color, a);
  }
}

/* ================================================================== *
 * 5x7 bitmap font — enough for the chrome labels in the mock
 * ================================================================== */

const GLYPHS = {
  A: "01110,10001,10001,11111,10001,10001,10001",
  B: "11110,10001,10001,11110,10001,10001,11110",
  C: "01110,10001,10000,10000,10000,10001,01110",
  D: "11110,10001,10001,10001,10001,10001,11110",
  E: "11111,10000,10000,11110,10000,10000,11111",
  F: "11111,10000,10000,11110,10000,10000,10000",
  G: "01110,10001,10000,10111,10001,10001,01111",
  H: "10001,10001,10001,11111,10001,10001,10001",
  I: "11111,00100,00100,00100,00100,00100,11111",
  J: "00111,00010,00010,00010,00010,10010,01100",
  K: "10001,10010,10100,11000,10100,10010,10001",
  L: "10000,10000,10000,10000,10000,10000,11111",
  M: "10001,11011,10101,10101,10001,10001,10001",
  N: "10001,11001,10101,10011,10001,10001,10001",
  O: "01110,10001,10001,10001,10001,10001,01110",
  P: "11110,10001,10001,11110,10000,10000,10000",
  Q: "01110,10001,10001,10001,10101,10010,01101",
  R: "11110,10001,10001,11110,10100,10010,10001",
  S: "01111,10000,10000,01110,00001,00001,11110",
  T: "11111,00100,00100,00100,00100,00100,00100",
  U: "10001,10001,10001,10001,10001,10001,01110",
  V: "10001,10001,10001,10001,10001,01010,00100",
  W: "10001,10001,10001,10101,10101,11011,10001",
  X: "10001,10001,01010,00100,01010,10001,10001",
  Y: "10001,10001,01010,00100,00100,00100,00100",
  Z: "11111,00001,00010,00100,01000,10000,11111",
  0: "01110,10011,10101,10101,11001,10001,01110",
  1: "00100,01100,00100,00100,00100,00100,01110",
  2: "01110,10001,00001,00110,01000,10000,11111",
  3: "11111,00010,00100,00010,00001,10001,01110",
  4: "00010,00110,01010,10010,11111,00010,00010",
  5: "11111,10000,11110,00001,00001,10001,01110",
  6: "00110,01000,10000,11110,10001,10001,01110",
  7: "11111,00001,00010,00100,01000,01000,01000",
  8: "01110,10001,10001,01110,10001,10001,01110",
  9: "01110,10001,10001,01111,00001,00010,01100",
  " ": "00000,00000,00000,00000,00000,00000,00000",
  ".": "00000,00000,00000,00000,00000,01100,01100",
  "-": "00000,00000,00000,11111,00000,00000,00000",
  "%": "11001,11011,00110,01100,11011,10011,00000",
  "/": "00001,00010,00010,00100,01000,01000,10000",
  ":": "00000,01100,01100,00000,01100,01100,00000",
};

function text(str, x, y, scale, color, a = 1, tracking = 1) {
  let cursor = x;
  for (const ch of str.toUpperCase()) {
    const glyph = GLYPHS[ch];
    if (glyph) {
      const rows = glyph.split(",");
      for (let r = 0; r < rows.length; r++) {
        for (let c = 0; c < 5; c++) {
          if (rows[r][c] === "1") {
            rect(cursor + c * scale, y + r * scale, scale, scale, color, a);
          }
        }
      }
    }
    cursor += (5 + tracking) * scale;
  }
  return cursor;
}

/* ================================================================== *
 * Compose the mock
 * ================================================================== */

clear(BG);

// Instrument grid: two frequencies, faded toward the edges so it reads as a
// measuring surface rather than graph paper.
for (let x = 0; x < W; x += 24) {
  const major = x % 96 === 0;
  for (let y = 0; y < H; y++) {
    const fade = 1 - Math.min(1, Math.hypot((x - W / 2) / (W / 2), (y - H / 2.6) / (H / 2)));
    px(x, y, LINE, (major ? 0.05 : 0.028) * fade);
  }
}
for (let y = 0; y < H; y += 24) {
  const major = y % 96 === 0;
  for (let x = 0; x < W; x++) {
    const fade = 1 - Math.min(1, Math.hypot((x - W / 2) / (W / 2), (y - H / 2.6) / (H / 2)));
    px(x, y, LINE, (major ? 0.05 : 0.028) * fade);
  }
}

// Aurora wash, matching the default background mode.
for (const [cx, cy, radius] of [
  [250, 60, 420],
  [900, 20, 380],
]) {
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const d = Math.hypot(x - cx, y - cy) / radius;
      if (d < 1) px(x, y, ACCENT, (1 - d) ** 2 * 0.075);
    }
  }
}

/* ---- Header ---- */
diamond(44, 40, 6, ACCENT, 0.9);
frame(38, 34, 13, 13, ACCENT, 0.5);
text("OBSERVER", 66, 33, 2, TEXT, 0.95, 2);

text("FLEET", 700, 35, 1, ACCENT, 0.9, 2);
text("LATENCY", 776, 35, 1, MUTED, 0.7, 2);
text("UPTIME", 884, 35, 1, MUTED, 0.7, 2);

// Connection tier badge — the piece of chrome unique to this theme.
frame(1000, 30, 158, 22, LINE, 0.22);
rect(1012, 39, 5, 5, OK, 1);
text("LIVE", 1026, 37, 1, TEXT, 0.9, 2);
text("RPC-WS", 1076, 37, 1, FAINT, 0.85, 2);

line(40, 72, W - 40, 72, LINE, 0.22);
line(40, 72, 340, 72, ACCENT, 0.35);

/* ---- Summary strip ---- */
const stats = [
  ["ONLINE", "23/24"],
  ["AVG CPU", "34.2%"],
  ["MEMORY", "58%"],
  ["NETWORK", "14.2M/S"],
  ["TRAFFIC", "8.4T"],
];
rect(40, 92, W - 80, 58, [255, 255, 255], 0.035);
frame(40, 92, W - 80, 58, LINE, 0.16);
stats.forEach(([label, value], i) => {
  const x = 40 + i * ((W - 80) / stats.length);
  if (i > 0) line(x, 92, x, 150, LINE, 0.14);
  text(label, x + 18, 106, 1, FAINT, 0.9, 2);
  text(value, x + 18, 122, 2, TEXT, 0.95, 1);
});

/* ---- Node cards ---- */
const CARD_W = 364;
const CARD_H = 196;
const cards = [
  { name: "TOKYO-01", cpu: 34, mem: 48, disk: 62, status: OK, spark: [4, 9, 6, 14, 11, 18, 13, 22, 17, 25, 20, 28, 24, 21, 27] },
  { name: "FRA-02", cpu: 72, mem: 81, disk: 45, status: WARN, spark: [22, 18, 26, 20, 29, 24, 31, 26, 33, 28, 24, 30, 26, 32, 28] },
  { name: "SGP-03", cpu: 8, mem: 22, disk: 31, status: OK, spark: [3, 5, 4, 7, 5, 8, 6, 9, 7, 6, 8, 5, 9, 6, 7] },
  { name: "NYC-04", cpu: 0, mem: 0, disk: 0, status: BAD, spark: [] },
  { name: "LON-05", cpu: 51, mem: 39, disk: 88, status: OK, spark: [12, 16, 14, 19, 15, 21, 18, 23, 19, 24, 21, 26, 22, 25, 23] },
  { name: "SYD-06", cpu: 19, mem: 55, disk: 27, status: OK, spark: [7, 11, 9, 13, 10, 15, 12, 14, 11, 16, 13, 17, 14, 18, 15] },
];

cards.forEach((card, i) => {
  const col = i % 3;
  const row = Math.floor(i / 3);
  const x = 40 + col * (CARD_W + 22);
  const y = 172 + row * (CARD_H + 20);
  const offline = card.status === BAD;
  const alpha = offline ? 0.55 : 1;

  rect(x, y, CARD_W, CARD_H, [255, 255, 255], 0.04 * alpha);
  frame(x, y, CARD_W, CARD_H, LINE, 0.18 * alpha);
  rect(x, y, 2, CARD_H, card.status, 0.85 * alpha);

  rect(x + 18, y + 20, 6, 6, card.status, alpha);
  text(card.name, x + 34, y + 17, 2, TEXT, 0.92 * alpha, 1);
  text(["JP", "DE", "SG", "US", "GB", "AU"][i], x + CARD_W - 42, y + 18, 1, FAINT, 0.85 * alpha, 2);

  // Three-quarter arc gauges, starting at 135 degrees like the real component.
  const gauges = [
    ["CPU", card.cpu],
    ["MEM", card.mem],
    ["DSK", card.disk],
  ];
  gauges.forEach(([label, value], gi) => {
    const gx = x + 74 + gi * 108;
    const gy = y + 90;
    const r = 28;
    arc(gx, gy, r, 135, 270, 3, LINE, 0.2 * alpha);
    if (!offline) {
      const tone = value >= 90 ? BAD : value >= 75 ? WARN : ACCENT;
      arc(gx, gy, r, 135, 270 * (value / 100), 3, tone, 0.95);
    }
    const label2 = offline ? "--" : String(value);
    const width = label2.length * 6 * 2 - 2;
    text(label2, gx - width / 2, gy - 7, 2, TEXT, 0.9 * alpha, 1);
    text(label, gx - 11, gy + 34, 1, FAINT, 0.9 * alpha, 2);
  });

  // Sparkline
  const sx = x + 18;
  const sy = y + CARD_H - 26;
  const sw = 220;
  const sh = 26;
  if (card.spark.length > 1) {
    const max = Math.max(...card.spark);
    for (let p = 0; p < card.spark.length - 1; p++) {
      const x0 = sx + (p * sw) / (card.spark.length - 1);
      const x1 = sx + ((p + 1) * sw) / (card.spark.length - 1);
      const y0 = sy + sh - (card.spark[p] / max) * sh;
      const y1 = sy + sh - (card.spark[p + 1] / max) * sh;
      // Fill every column in the span, not just the left edge, so the area
      // reads as a wash rather than a hatch.
      for (let xx = x0; xx <= x1; xx += 0.5) {
        const yTop = y0 + ((y1 - y0) * (xx - x0)) / Math.max(0.5, x1 - x0);
        for (let yy = yTop; yy < sy + sh; yy++) px(xx, yy, ACCENT, 0.09);
      }
      line(x0, y0, x1, y1, ACCENT, 0.9);
    }
    text("1.2M", x + CARD_W - 92, sy + 2, 1, ACCENT, 0.85, 2);
    text("840K", x + CARD_W - 92, sy + 14, 1, MUTED, 0.7, 2);
  } else {
    text("OFFLINE", sx, sy + 8, 1, FAINT, 0.8, 2);
  }
});

/* ---- Footer ---- */
line(40, H - 44, W - 40, H - 44, LINE, 0.18);
text("POWERED BY KOMARI MONITOR.", 40, H - 30, 1, FAINT, 0.8, 2);
text("OBSERVER", W - 150, H - 30, 1, FAINT, 0.8, 2);

/* ================================================================== *
 * PNG encoding
 * ================================================================== */

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(bytes) {
  let c = 0xffffffff;
  for (const byte of bytes) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length, 0);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body), 0);
  return Buffer.concat([length, body, crc]);
}

const ihdr = Buffer.alloc(13);
ihdr.writeUInt32BE(W, 0);
ihdr.writeUInt32BE(H, 4);
ihdr[8] = 8; // bit depth
ihdr[9] = 6; // colour type: RGBA
ihdr[10] = 0; // deflate
ihdr[11] = 0; // adaptive filtering
ihdr[12] = 0; // no interlace

// Each scanline is prefixed with its filter type; 0 (None) keeps this simple
// and still compresses well for flat-ish UI artwork.
const raw = Buffer.alloc(H * (W * 4 + 1));
for (let y = 0; y < H; y++) {
  const offset = y * (W * 4 + 1);
  raw[offset] = 0;
  Buffer.from(buf.buffer, y * W * 4, W * 4).copy(raw, offset + 1);
}

const png = Buffer.concat([
  Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
  chunk("IHDR", ihdr),
  chunk("IDAT", deflateSync(raw, { level: 9 })),
  chunk("IEND", Buffer.alloc(0)),
]);

writeFileSync("preview.png", png);
console.log(`✓ preview.png (${W}x${H}, ${(png.length / 1024).toFixed(1)} KB)`);
